### ISSUE TITLE
Add functionality to delete a card

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/plastic#11]
The question would be where to "put" the functionality in terms of UX. Any ideas @gustavkarlsson?

**Comment by gustavkarlsson** [comment]
Action bar? Probably in the overflow menu since it's probably not a commonly used action.

**Comment by karllindmark** [comment]
Is this in the actual "detail screen" for a card, or should it be available in the listing too? @gustavkarlsson

**Comment by gustavkarlsson** [comment]
Yeah, first of all in the detail screen. But putting it in the listing too might avoid some confusion. I'd say both :)

**Comment by karllindmark** [comment]
I've added it to the detail screen, and will create a new issue re: the list as well (need to think a bit on how to add it).
