### ISSUE TITLE
Add "verified by visa" or similar for supported vendors

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/plastic#16]
> Would be cool with a "Verified by VISA" and mastercard equivalent password field for cards that support it

This is great @gustavkarlsson, why didn't I think of that? :dancer:

Should I display it all the time, or just for VISA/MasterCard derivatives? I'm not completely sure if (for example) JCB sports that feature too.

**Comment by gustavkarlsson** [comment]
IMO: Start by adding only the known ones

**Comment by karllindmark** [comment]
:+1:

**Comment by karllindmark** [comment]
Verified by VISA and MasterCard SecureCode added!
