### ISSUE TITLE
App looks crazy in landscape

### ISSUE THREAD

**Issue by karllindmark** [ninetwozero/plastic#3]
As per what @ejanuszewski said:

> Also restrict to portrait as landscape cardview is kinda crazy, or make it scale

It should probably scale better, but that hasn't been a priority so far. Soon&trade;!

**Comment by karllindmark** [comment]
TODO:
- [x] Onboarding
- [x] Listing
- [ ] Details

**Comment by karllindmark** [comment]
^------- One down, three to go!
@ejanuszewski @gustavkarlsson

**Comment by karllindmark** [comment]
The next time you hear from me in this thread the listing won't look like this in landscape anymore:

<img src="https://cloud.githubusercontent.com/assets/979152/9864537/ec46719c-5b4a-11e5-91e3-924a3c78e2b8.png" width="40%" height="40%">

:8ball:

**Comment by karllindmark** [comment]
A bit better now, eh?

<img src="https://cloud.githubusercontent.com/assets/979152/9979054/cad82a96-5f55-11e5-857c-50dec96e29a7.png" width="80%" height="80%">

@gustavkarlsson @ejanuszewski

**Comment by gustavkarlsson** [comment]
Looks awesome!

**Comment by karllindmark** [comment]
The app doesn't look crazy anymore. At least I think it doesn't.
